-- CORDIC.vhd

-- Generated using ACDS version 19.1 670

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CORDIC is
	port (
		a      : in  std_logic_vector(17 downto 0) := (others => '0'); --      a.a
		areset : in  std_logic                     := '0';             -- areset.reset
		clk    : in  std_logic                     := '0';             --    clk.clk
		x      : in  std_logic_vector(16 downto 0) := (others => '0'); --      x.x
		xo     : out std_logic_vector(17 downto 0);                    --     xo.xo
		y      : in  std_logic_vector(16 downto 0) := (others => '0'); --      y.y
		yo     : out std_logic_vector(17 downto 0)                     --     yo.yo
	);
end entity CORDIC;

architecture rtl of CORDIC is
	component CORDIC_CORDIC_0 is
		port (
			clk    : in  std_logic                     := 'X';             -- clk
			areset : in  std_logic                     := 'X';             -- reset
			x      : in  std_logic_vector(16 downto 0) := (others => 'X'); -- x
			y      : in  std_logic_vector(16 downto 0) := (others => 'X'); -- y
			a      : in  std_logic_vector(17 downto 0) := (others => 'X'); -- a
			xo     : out std_logic_vector(17 downto 0);                    -- xo
			yo     : out std_logic_vector(17 downto 0)                     -- yo
		);
	end component CORDIC_CORDIC_0;

begin

	cordic_0 : component CORDIC_CORDIC_0
		port map (
			clk    => clk,    --    clk.clk
			areset => areset, -- areset.reset
			x      => x,      --      x.x
			y      => y,      --      y.y
			a      => a,      --      a.a
			xo     => xo,     --     xo.xo
			yo     => yo      --     yo.yo
		);

end architecture rtl; -- of CORDIC
